In [1]:
!pip install nltk

In [9]:
import torch
from sklearn.model_selection import train_test_split
import pandas as pd
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset,DataLoader
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter



In [11]:
document = """
VSky Solutions is a software development and technology services company.
The company provides custom software solutions and application development services.
VSky Solutions works in areas such as data science, data engineering, data analysis,
Power BI, data integration, data migration, CRM, ERP, web application development,
and mobile application development.

The company focuses on developing customized technology solutions for businesses.
Software development is one of the major areas of its work.
The company also works with data and business intelligence solutions.
Data analysis and Power BI can be used to transform business data into useful
reports, dashboards, and insights.

Data integration connects information from different systems and applications.
Data migration involves transferring data from one system to another while
maintaining data accuracy and consistency.
CRM solutions help organizations manage customer and contact information,
while ERP solutions support business operations and enterprise processes.

VSky Solutions also provides custom web application development.
Web applications can be designed according to specific business requirements.
Application development involves designing the application, implementing the
backend and frontend, connecting databases, testing the application, and
maintaining the system.

The company has operations associated with Kolhapur, Maharashtra, India,
and also has a presence in Jacksonville, Florida.
VSky Solutions was originally established as Yash Creations and was later
rebranded as VSky Solutions.
The company works on software development and digital technology solutions.

Technology solutions can help organizations improve their business processes.
Data engineering helps collect, process, transform, and organize data.
Data analysis helps identify patterns and useful information from business data.
Business intelligence tools such as Power BI can be used to create interactive
dashboards and reports.

A software project generally begins with understanding business requirements.
After requirements are identified, developers design the application architecture.
The development team then implements the required features and integrates
the application with databases and external systems.
Testing is performed to identify errors and verify that the application works
as expected.

Data integration is important when an organization uses multiple systems.
Different applications may store different types of business information.
Integration allows these systems to exchange information and work together.
Data migration may be required when an organization changes its existing
software or database system.

CRM and ERP systems can be integrated with custom applications.
Such integrations can allow customer information, business information,
and operational data to move between systems.
APIs are commonly used to connect different software applications.
An API provides a structured way for one application to communicate with
another application.

Software development requires programming, database management, testing,
deployment, and maintenance.
A development team may work on frontend applications, backend services,
databases, APIs, and integrations.
Good software should be reliable, maintainable, scalable, and secure.

VSky Solutions provides technology services focused on software development,
data solutions, business intelligence, application development, and system
integration.
"""

In [7]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [12]:
tokens = word_tokenize(document.lower())

In [13]:
# build vocab
vocab = {'<unk>':0}

for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)

vocab

{'<unk>': 0,
 'vsky': 1,
 'solutions': 2,
 'is': 3,
 'a': 4,
 'software': 5,
 'development': 6,
 'and': 7,
 'technology': 8,
 'services': 9,
 'company': 10,
 '.': 11,
 'the': 12,
 'provides': 13,
 'custom': 14,
 'application': 15,
 'works': 16,
 'in': 17,
 'areas': 18,
 'such': 19,
 'as': 20,
 'data': 21,
 'science': 22,
 ',': 23,
 'engineering': 24,
 'analysis': 25,
 'power': 26,
 'bi': 27,
 'integration': 28,
 'migration': 29,
 'crm': 30,
 'erp': 31,
 'web': 32,
 'mobile': 33,
 'focuses': 34,
 'on': 35,
 'developing': 36,
 'customized': 37,
 'for': 38,
 'businesses': 39,
 'one': 40,
 'of': 41,
 'major': 42,
 'its': 43,
 'work': 44,
 'also': 45,
 'with': 46,
 'business': 47,
 'intelligence': 48,
 'can': 49,
 'be': 50,
 'used': 51,
 'to': 52,
 'transform': 53,
 'into': 54,
 'useful': 55,
 'reports': 56,
 'dashboards': 57,
 'insights': 58,
 'connects': 59,
 'information': 60,
 'from': 61,
 'different': 62,
 'systems': 63,
 'applications': 64,
 'involves': 65,
 'transferring': 66,
 'syst

In [14]:
len(vocab)

184

In [15]:
input_sentences = document.split('\n')

In [16]:
def text_to_indices(sentence, vocab):

  numerical_sentence = []

  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence


In [17]:
input_numerical_sentences = []

for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))


In [18]:
len(input_numerical_sentences)

67

In [19]:
training_sequence = []
for sentence in input_numerical_sentences:

  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [20]:
len(training_sequence)

479

In [21]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5, 6]]

In [22]:
len_list = []

for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

17

In [24]:
training_sequence[10]

[12, 10]

In [25]:
padded_training_sequence = []
for sequence in training_sequence:

  padded_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [26]:
len(padded_training_sequence[10])

17

In [27]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype=torch.long)

In [28]:
padded_training_sequence

tensor([[ 0,  0,  0,  ...,  0,  1,  2],
        [ 0,  0,  0,  ...,  1,  2,  3],
        [ 0,  0,  0,  ...,  2,  3,  4],
        ...,
        [ 0,  0,  0,  ...,  6, 23,  7],
        [ 0,  0,  0,  ..., 23,  7, 67],
        [ 0,  0,  0,  ...,  0, 28, 11]])

In [29]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:,-1]

In [30]:
X

tensor([[ 0,  0,  0,  ...,  0,  0,  1],
        [ 0,  0,  0,  ...,  0,  1,  2],
        [ 0,  0,  0,  ...,  1,  2,  3],
        ...,
        [ 0,  0,  0,  ..., 15,  6, 23],
        [ 0,  0,  0,  ...,  6, 23,  7],
        [ 0,  0,  0,  ...,  0,  0, 28]])

In [31]:
y

tensor([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  10,  13,  14,   5,
          2,   7,  15,   6,   9,  11,   2,  16,  17,  18,  19,  20,  21,  22,
         23,  21,  24,  23,  21,  25,  23,  27,  23,  21,  28,  23,  21,  29,
         23,  30,  23,  31,  23,  32,  15,   6,  23,  33,  15,   6,  11,  10,
         34,  35,  36,  37,   8,   2,  38,  39,  11,   6,   3,  40,  41,  12,
         42,  18,  41,  43,  44,  11,  10,  45,  16,  46,  21,   7,  47,  48,
          2,  11,  25,   7,  26,  27,  49,  50,  51,  52,  53,  47,  21,  54,
         55,  23,  57,  23,   7,  58,  11,  28,  59,  60,  61,  62,  63,   7,
         64,  11,  29,  65,  66,  21,  61,  40,  67,  52,  68,  69,  21,  71,
          7,  72,  11,   2,  73,  74,  75,  76,   7,  77,  60,  23,  31,   2,
         78,  47,  79,   7,  80,  81,  11,   2,  45,  13,  14,  32,  15,   6,
         11,  64,  49,  50,  82,  83,  52,  84,  47,  85,  11,   6,  65,  86,
         12,  15,  23,  87,  12,   7,  89,  23,  90,  91,  23,  

In [32]:
class CustomDataset(Dataset):

  def __init__(self, X, y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

In [33]:
dataset = CustomDataset(X,y)

In [34]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [35]:
class LSTMModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 100)
    self.lstm = nn.LSTM(100, 150, batch_first=True)
    self.fc = nn.Linear(150, vocab_size)

  def forward(self, x):
    embedded = self.embedding(x)
    intermediate_hidden_states, (final_hidden_state, final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [36]:
model = LSTMModel(len(vocab))

In [37]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [38]:
model.to(device)

LSTMModel(
  (embedding): Embedding(184, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=184, bias=True)
)

In [39]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [40]:
for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 77.5631
Epoch: 2, Loss: 71.0156
Epoch: 3, Loss: 65.8931
Epoch: 4, Loss: 62.3908
Epoch: 5, Loss: 58.4407
Epoch: 6, Loss: 54.5353
Epoch: 7, Loss: 50.5496
Epoch: 8, Loss: 46.7905
Epoch: 9, Loss: 43.0502
Epoch: 10, Loss: 39.4170
Epoch: 11, Loss: 36.1367
Epoch: 12, Loss: 32.9226
Epoch: 13, Loss: 29.7571
Epoch: 14, Loss: 26.8817
Epoch: 15, Loss: 24.2615
Epoch: 16, Loss: 21.8683
Epoch: 17, Loss: 19.8278
Epoch: 18, Loss: 17.6518
Epoch: 19, Loss: 15.9212
Epoch: 20, Loss: 14.3625
Epoch: 21, Loss: 12.9570
Epoch: 22, Loss: 11.7386
Epoch: 23, Loss: 10.7436
Epoch: 24, Loss: 9.7718
Epoch: 25, Loss: 8.9469
Epoch: 26, Loss: 8.2328
Epoch: 27, Loss: 7.6242
Epoch: 28, Loss: 7.0640
Epoch: 29, Loss: 6.6028
Epoch: 30, Loss: 6.1988
Epoch: 31, Loss: 5.7846
Epoch: 32, Loss: 5.4591
Epoch: 33, Loss: 5.2039
Epoch: 34, Loss: 4.9425
Epoch: 35, Loss: 4.7402
Epoch: 36, Loss: 4.4901
Epoch: 37, Loss: 4.3067
Epoch: 38, Loss: 4.1791
Epoch: 39, Loss: 4.0075
Epoch: 40, Loss: 3.8675
Epoch: 41, Loss: 3.7513
Ep

In [41]:
# prediction

def prediction(model, vocab, text):

  # tokenize
  tokenized_text = word_tokenize(text.lower())

  # text -> numerical indices
  numerical_text = text_to_indices(tokenized_text, vocab)

  # padding
  padded_text = torch.tensor([0] * (61 - len(numerical_text)) + numerical_text, dtype=torch.long).unsqueeze(0)

  # send to model
  output = model(padded_text)

  # predicted index
  value, index = torch.max(output, dim=1)

  # merge with text
  return text + " " + list(vocab.keys())[index]

In [42]:
prediction(model, vocab, "The course follows a monthly")

'The course follows a monthly software'

In [44]:
import time

num_tokens = 10
input_text = "Software Development"

for i in range(num_tokens):
  output_text = prediction(model, vocab, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


Software Development is
Software Development is one
Software Development is one of
Software Development is one of the
Software Development is one of the major
Software Development is one of the major areas
Software Development is one of the major areas of
Software Development is one of the major areas of its
Software Development is one of the major areas of its work
Software Development is one of the major areas of its work .


In [45]:
dataloader1 = DataLoader(dataset, batch_size=32, shuffle=False)

In [46]:
# Function to calculate accuracy
def calculate_accuracy(model, dataloader, device):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    total = 0

    with torch.no_grad():  # No need to compute gradients
        for batch_x, batch_y in dataloader1:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)

            # Get model predictions
            outputs = model(batch_x)

            # Get the predicted word indices
            _, predicted = torch.max(outputs, dim=1)

            # Compare with actual labels
            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy

# Compute accuracy
accuracy = calculate_accuracy(model, dataloader, device)
print(f"Model Accuracy: {accuracy:.2f}%")


Model Accuracy: 94.36%
