In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


Create Tensor

In [ ]:
# using empty
torch.empty(2,3)

tensor([[1.0380e-26, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [ ]:
a=torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.9439, 0.9275, 0.7403],
        [0.5333, 0.2473, 0.1948]])

In [ ]:
# use of seed(we get different rand everytime so use seed)
torch.rand(2,3)

tensor([[0.8835, 0.7297, 0.1983],
        [0.2314, 0.1058, 0.1279]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shape

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#shape
x.shape

torch.Size([2, 3])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

Tensor Data Types

In [ ]:
#find datatype
x.dtype

torch.int64

In [ ]:
#assign datatype
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#using to() change if already created
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# **Mathematical Operations**

#scalar opern


In [ ]:

x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
#addition
x+2

tensor([[2.2627, 2.0428],
        [2.2080, 2.1180]])

In [ ]:
#substraction
x-2

tensor([[-1.7373, -1.9572],
        [-1.7920, -1.8820]])

In [ ]:
#multiply
x * 3

tensor([[0.7881, 0.1285],
        [0.6241, 0.3541]])

In [ ]:
#division
x / 3

tensor([[0.0876, 0.0143],
        [0.0693, 0.0393]])

In [ ]:
#int division
(x * 100) // 3

tensor([[8., 1.],
        [6., 3.]])

In [ ]:
#x mode
((x * 100) // 3)%2

tensor([[0., 1.],
        [0., 1.]])

In [ ]:
#power
x**3

tensor([[1.8127e-02, 7.8621e-05],
        [9.0026e-03, 1.6446e-03]])

#elementwise operations

In [ ]:
a =  torch.rand(2,2)
b =  torch.rand(2,2)
print(a)
print(b)

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])
tensor([[0.4183, 0.9014],
        [0.9969, 0.7565]])


In [ ]:
#add
a + b
#sub
a - b
#multiply
a * b
#division
a / b
#power
a ** b
# mod
a % b

tensor([[0.1217, 0.7356],
        [0.7118, 0.0311]])

In [ ]:
#absolute
c = torch.tensor([1, -2, 3, -4])
print(c)
torch.abs(c)

tensor([ 1, -2,  3, -4])


tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9,2.7,3.5,4.4])

In [ ]:
#round
torch.round(d)

tensor([2., 3., 4., 4.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp
torch.clamp(d, min=1.5, max=3.5)

tensor([1.9000, 2.7000, 3.5000, 3.5000])

#reduction opern

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10)
e

tensor([[4, 3, 8],
        [7, 4, 6]])

In [ ]:
#sum (of whole matrix)
torch.sum(e)

tensor(32)

In [ ]:
#sum along col
torch.sum(e, dim=0)

tensor([11,  7, 14])

In [ ]:
#sum along row
torch.sum(e, dim=1)

tensor([15, 17])

In [ ]:
f = torch.randint(size=(2,3),low=0,high=10 ,dtype = torch.float32)
f

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [ ]:
#mean (will work for float )
torch.mean(f)

tensor(4.5000)

In [ ]:
#mean along col
torch.mean(f, dim=0)

tensor([4.5000, 4.5000, 4.5000])

In [ ]:
#meadian
torch.median(e)

tensor(4)

In [ ]:
#max and Min
torch.min(e)
torch.max(e)

tensor(8)

In [ ]:
#product
torch.prod(e)

tensor(16128)

In [ ]:
#standard deviation(supports only float)
torch.std(f)

tensor(4.5935)

In [ ]:
#variance
torch.var(f)

tensor(21.1000)

In [ ]:
#argmax (positon of max value)
torch.argmax(f)

tensor(2)

In [ ]:
#argmin (position of min value)
torch.argmin(f)

tensor(0)

##matrix opern

In [ ]:
g = torch.randint(size=(2,3),low=0, high=10)
h = torch.randint(size=(3,2),low=0, high=10)

print(g)
print(h)

tensor([[7, 0, 0],
        [9, 5, 7]])
tensor([[3, 9],
        [4, 0],
        [5, 7]])


In [ ]:
#matrix multiplication
torch.matmul(g,h)

tensor([[ 21,  63],
        [ 82, 130]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[0., 9.],
        [1., 8.],
        [9., 0.]])

In [ ]:
#determinant (float value and must be square matrix)
i =torch.randint(size =(3,3),low=0 ,high=10, dtype=torch.float32)
torch.det(i)

tensor(184.0000)

In [ ]:
#inverse
torch.inverse(i)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

#comparison opern




In [ ]:
j = torch.randint(size=(3,3),low=0, high=10)
k = torch.randint(size=(3,3),low=0, high=10)

print(j)
print(k)

tensor([[9, 2, 6],
        [7, 7, 8],
        [3, 6, 1]])
tensor([[5, 5, 0],
        [4, 3, 8],
        [8, 3, 3]])


In [ ]:
# greater than
j > k
# less than
j < k
# equal to
j == k
# not equal to
j != k
# greater than equal to
j >= k
# less than equal to
j <= k

tensor([[False,  True, False],
        [False, False,  True],
        [ True, False,  True]])

In [ ]:
l = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
l

tensor([[5., 0., 6.],
        [4., 0., 8.]])

In [ ]:
#log
torch.log(l)

tensor([[1.6094,   -inf, 1.7918],
        [1.3863,   -inf, 2.0794]])

In [ ]:
#exp
torch.exp(l)

tensor([[1.4841e+02, 1.0000e+00, 4.0343e+02],
        [5.4598e+01, 1.0000e+00, 2.9810e+03]])

In [ ]:
#sqrt
torch.sqrt(l)

tensor([[2.2361, 0.0000, 2.4495],
        [2.0000, 0.0000, 2.8284]])

In [ ]:
#sigmoid
torch.sigmoid(l)

tensor([[0.9933, 0.5000, 0.9975],
        [0.9820, 0.5000, 0.9997]])

In [ ]:
#softmax
torch.softmax(l, dim=1)

tensor([[2.6845e-01, 1.8088e-03, 7.2974e-01],
        [1.7980e-02, 3.2932e-04, 9.8169e-01]])

In [ ]:
#relu(if 0 or negative then 0 else same value)
torch.relu(l)

tensor([[5., 0., 6.],
        [4., 0., 8.]])

#Inplace opern

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])
tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])


In [ ]:
m.add_(n)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
m

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [ ]:
n

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
m.relu_() #use instead of torch.relu(m)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

#Copying a tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
b = a #(if we will make chananges in a b will also change)
b

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
id(a)

133179185170864

In [ ]:
id(b)

133179185170864

In [ ]:
b = a.clone()
a
b

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

#Tensor Operation on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# Creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor on GPU
a = torch.rand(2,3)
a

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [ ]:
b = a.to(device)
b

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]], device='cuda:0')